// Auto-generated types from Database schemas
// This file is generated by scripts/schema-watch.script.js

import { type Infer } from "convex/values";

import { addresses } from "./convex/schemas/address.schema";
import { brands } from "./convex/schemas/brand.schema";
import { menu_items } from "./convex/schemas/menu.item.schema";
import { menus } from "./convex/schemas/menu.schema";
import { orderItems } from "./convex/schemas/order.items.schema";
import { orders } from "./convex/schemas/order.schema";
import { restaurants } from "./convex/schemas/restaurant.schema";
import { users } from "./convex/schemas/users.schema";

export type Addresses = Infer<typeof addresses.validator>;
export type Brands = Infer<typeof brands.validator>;
export type MenuItems = Infer<typeof menu_items.validator>;
export type Menus = Infer<typeof menus.validator>;
export type Orderitems = Infer<typeof orderItems.validator>;
export type Orders = Infer<typeof orders.validator>;
export type Restaurants = Infer<typeof restaurants.validator>;
export type Users = Infer<typeof users.validator>;
